baseURL = 'https://www.girtonspringball.com/'
languageCode = 'en-us'
title = 'GSB 2025'

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Welcome to the absurd world of the Girton Spring Ball! We are so excited to welcome you on Friday 21st March 2025! A link to the ticketing platform can be found here as well as all the information you need for the night. Our vision for the 2025 ball is to revive and celebrate the Girton community by way of a fun and responsible full-scale party. The theme perfectly reflects both the strangeness of recent collective experience whilst also celebrating the creativity and light-heartedness of our long history of Spring Balls. As Camus said “The realisation that life is absurd cannot be an end, but only a beginning…”. We mean to start as we mean to go on."
